---
title: "Making a Stem and Leaf Plot"
# author: "John Minter"
date: "Last updated: 2018-06-03"
output:
  rmarkdown::html_vignette:
    number_sections: true
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Making a Stem and Leaf Plot}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
suppressWarnings(suppressMessages(suppressPackageStartupMessages(library(ggplot2))))
```
# Introduction

This example is adapted from data supplied by
[https://www.statcan.gc.ca](https://www.statcan.gc.ca/edu/power-pouvoir/ch8/5214816-eng.htm#a3).

# Analysis

## Input the data

The weights (to the nearest tenth of a kilogram) of 30 students were measured
and recorded as follows:

```{r inputData}
dat <- c(59.2, 61.5, 62.3, 61.4, 60.9, 59.8,
		 60.5, 59.0, 61.1, 60.7, 61.6, 56.3,
		 61.9, 65.7, 60.4, 58.9, 59.0, 61.2,
		 62.1, 61.4, 58.4, 60.8, 60.2, 62.7,
		 60.0, 59.3, 61.9, 61.7, 58.4, 62.2)
```

## Make the plots

```{r makePlot, fig.width=6.5}
library(statshelpR)
print(stem.leaf.plot(dat))
```

## Summary

Note the location of the decimal in this example. The numbers beyond
the vertical bar are the values in tenths of kg.
